# Generated by Django 6.0.5 on 2026-06-01 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imgUrl', models.URLField(help_text='Paste any image URL (Unsplash, Amazon, etc.)', max_length=500)),
                ('shortDesc', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('avgRating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('inStock', models.BooleanField(default=True)),
                ('discount', models.IntegerField(default=0, help_text='Discount % (0 = no discount)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
